name: Plausible-py

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff bandit
          pip install -r requirements.txt
      - name: Linting with Ruff
        run: ruff check .
      - name: Test with pytest
        run: pytest tests
      - name: Check vulnerability with Bandit
        run: bandit -r .
